### ISSUE TITLE
Need more robust error handling in token-exchange and jwt-refresh.

### ISSUE THREAD

**Issue by bhalsey** [FusionAuth/fusionauth-example-react-sdk#15]
The `token-exchange` and `jwt-refresh` endpoints currently return a 5xx response if not in the happy path.  The endpoints should handle the various error codes that can be returned with appropriate response codes that help the developer understand the underlying issue (e.g., misconfiguration, bad user request, etc.).

**Comment by JakeLo123** [comment]
[This PR](https://github.com/FusionAuth/fusionauth-example-react-sdk/pull/31) has handled this issue. Closing.
