### ISSUE TITLE
request http client is deprecated

### ISSUE THREAD

**Issue by JakeLo123** [FusionAuth/fusionauth-example-react-sdk#30]
### Problem
The http client used by the server -- [request](https://www.npmjs.com/package/request) -- was fully deprecated in 2020.

### Solution
Remove the dependency and either replace the functionality relies on it.
Alternatives:
- standard `fetch` api (no dependency required)
- [Node Fetch](https://www.npmjs.com/package/node-fetch)
- [Axios](https://blog.logrocket.com/how-to-make-http-requests-like-a-pro-with-axios/)
- [Got](https://www.npmjs.com/package/got)

### Alternatives/workarounds
Continue using the deprecated dependency.

**Comment by mooreds** [comment]
For basic HTTP request functionality, which alternative would you recommend?

**Comment by JakeLo123** [comment]
> For basic HTTP request functionality, which alternative would you recommend?

I'd use the standard `fetch` api that comes with node! It's equivocal to the browser `fetch` api. It's not a dependency that we have to upgrade, manage, or switch if it deprecates as opposed to axios or something like that.

**Comment by mooreds** [comment]
makes sense to me!

**Comment by mooreds** [comment]
I don't like using deprecated components, can you add this into the workstream, please?

**Comment by JakeLo123** [comment]
> I don't like using deprecated components, can you add this into the workstream, please?

I'll prioritize this one today 👍
